import Header from '@/components/header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from '@/components/sidebar/SideBar'
import HeaderRep from '@/components/header/HeaderRep'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nhat Hoang',
  description: 'Generated by create next app',
}

const RootLayout = ({ children })=>{
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body scroll-smooth`}>
        <Header />
        <HeaderRep />
        <div className='xl:mt-[73px] lg:mb-[72px]'>
          <div className='flex justify-center'>
            <div
              style={{ borderColor: '#b8b612' }}
              className='max-w-screen-3xl xl:border border-x border-b flex flex-1 justify-center bg-black'>
              <div className='flex flex-wrap justify-center text-p text-sm py-2.5 px-2.5'>
                <p className='me-1 font-medium text-center'>
                  {"Truy cập Phimmoiy.com nếu không vào được "}
                  <b>Phimmoi</b>
                </p>
              </div>
            </div>
          </div>
          <div className='flex justify-center'>
            <div className='max-w-screen-3xl h-10 bg-p flex flex-1 justify-center border-b c-border'>
              <div className='bg-p w-full flex text-p text-sm py-3'>
              </div>
            </div>
          </div>
          <div className='flex justify-center'>
            <div className='max-w-screen-3xl bg-p flex flex-1 lg:flex-row flex-col'>
              {children}
              <SideBar/>
            </div>
          </div>
          <div className='flex justify-center'>
            <div className='max-w-screen-3xl flex-1 bg-p'>
              <Footer/>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
export default RootLayout
